In [ ]:
pip install tabulate

Requirement already satisfied: tabulate in /usr/local/lib/python3.7/dist-packages (0.8.9)

In [ ]:
import math
import numpy as np
from tabulate import tabulate

In [ ]:
def sh(x, eps):
  x1 = 0
  k = 0
  while abs((x**(2*k+1))/(math.factorial(2*k+1)))/3 >= eps:
    x1+=(x**(2*k+1))/(math.factorial(2*k+1))
    k+=1
  return x1

In [ ]:
  def arctan(x, eps):
    if abs(x) >=1:
      x1 = np.sign(x)*(math.pi)/2
      k=0
      while abs(((-1)**k)*((x**((-2)*k-1))/(2*k+1))) >= eps:
        x1 -= ((-1)**k)*((x**((-2)*k-1))/(2*k+1))
        k+=1

    else:
      x1 = 0
      k=0
      while abs(((-1)**k)*(x**(2*k+1))/(2*k+1)) >= eps:
        x1 += ((-1)**k)*(x**(2*k+1))/(2*k+1)
        k+=1
    return x1

In [ ]:
def sq(x, eps):
  if x<0:
    return
  elif x >=1:
    p = x
    while abs(p - (1/2)*(p+x/p)) >= eps:
      p = (1/2)*(p+x/p)
  else:
    p = 1
    while abs(p - (1/2)*(p+x/p)) >= eps:
      p = (1/2)*(p+x/p)
  return p

In [ ]:
eps1 = 1e-6/3.3
eps2 = 1e-6/4.5
eps3 = 1e-6/3
eps = 1e-6

In [ ]:
x = np.linspace(0.01, 0.06, 11)

In [ ]:
table1 = [['x', 'Our shx', 'delta1', 'True shx', 'delta2']]
for i in x:
  table1.append([i, sh(2*i+0.45, eps1), eps1, math.sinh(2*i+0.45), abs(math.sinh(2*i+0.45)-sh(2*i+0.45, eps1))])
print(tabulate(table1))

--------------------  -------------------  ----------------------  -------------------  ----------------------
x                     Our shx              delta1                  True shx             delta2
0.01                  0.48749595937710416  3.0303030303030305e-07  0.48749596246732974  3.090225575430594e-09
0.015                 0.4986455014581394   3.0303030303030305e-07  0.49864550519337625  3.735236842050682e-09
0.019999999999999997  0.5098449083882001   3.0303030303030305e-07  0.5098449128854814   4.49728132512206e-09
0.024999999999999998  0.5210953000992063   3.0303030303030305e-07  0.5210953054937474   5.394541036096712e-09
0.03                  0.5323978016192417   3.0303030303030305e-07  0.5323978080668103   6.4475685901399515e-09
0.034999999999999996  0.5437535431848067   3.0303030303030305e-07  0.5437535508643461   7.679539337779318e-09
0.039999999999999994  0.5551636603535711   3.0303030303030305e-07  0.5551636694700978   9.116526644703526e-09
0.045                 0.566629294117639    3.0303030303030305e-07  0.5666293049054345   1.0787795545752488e-08
0.049999999999999996  0.5781515910173303   3.0303030303030305e-07  0.5781516037434543   1.272612404346063e-08
0.05499999999999999   0.5897317032554952   3.0303030303030305e-07  0.5897317182236432   1.496814805435065e-08
0.06                  0.6013707888123675   3.0303030303030305e-07  0.6013708063670992   1.755473166831223e-08
--------------------  -------------------  ----------------------  -------------------  ----------------------

In [ ]:
table2 = [['x', 'Our arctgx', 'delta1', 'True arctgx', 'delta2']]
for i in x:
  table2.append([i, arctan(6*i+1, eps2), eps2, math.atan(6*i+1),abs(math.atan(6*i+1)-arctan(6*i+1, eps2)) ])
print(tabulate(table2))

--------------------  ------------------  ----------------------  ------------------  ----------------------
x                     Our arctgx          delta1                  True arctgx         delta2
0.01                  0.814516031585203   2.2222222222222222e-07  0.8145161449044872  1.1331928417845916e-07
0.015                 0.8284336655972979  2.2222222222222222e-07  0.8284337764208257  1.1082352779911986e-07
0.019999999999999997  0.8419414756051378  2.2222222222222222e-07  0.8419416003422656  1.2473712784899504e-07
0.024999999999999998  0.8550526203445181  2.2222222222222222e-07  0.8550527371260165  1.1678149836047425e-07
0.03                  0.8677801876215249  2.2222222222222222e-07  0.8677800939891389  9.363238595572199e-08
0.034999999999999996  0.8801361981787897  2.2222222222222222e-07  0.88013633141332    1.3323453029734367e-07
0.039999999999999994  0.8921339658096425  2.2222222222222222e-07  0.8921338360465839  1.2976305863166004e-07
0.045                 0.9037848040946108  2.2222222222222222e-07  0.9037846992443404  1.048502704659171e-07
0.049999999999999996  0.9151008063573647  2.2222222222222222e-07  0.9151007005533605  1.0580400422455227e-07
0.05499999999999999   0.926093427989788   2.2222222222222222e-07  0.9260932955034623  1.324863256879638e-07
0.06                  0.9367735022173903  2.2222222222222222e-07  0.9367736071314745  1.0491408419799342e-07
--------------------  ------------------  ----------------------  ------------------  ----------------------

In [ ]:
table3 = [['x', 'Our sqrt', 'delta1', 'True sqrt', 'delta2']]
for i in x:
  table3.append([i, sq(i, eps3), eps3, math.sqrt(i), abs(math.sqrt(i)-sq(i, eps3))])
print(tabulate(table3))

--------------------  -------------------  ---------------------  -------------------  ----------------------
x                     Our sqrt             delta1                 True sqrt            delta2
0.01                  0.10000000000139897  3.333333333333333e-07  0.1                  1.3989642777545441e-12
0.015                 0.12247452232801681  3.333333333333333e-07  0.1224744871391589   3.5188857910872784e-08
0.019999999999999997  0.14142135968022693  3.333333333333333e-07  0.1414213562373095   3.4429174233796545e-09
0.024999999999999998  0.1581138834410654   3.333333333333333e-07  0.15811388300841897  4.326464186910073e-10
0.03                  0.17320508082191835  3.333333333333333e-07  0.17320508075688773  6.503061977802815e-11
0.034999999999999996  0.1870828693498976   3.333333333333333e-07  0.18708286933869706  1.1200540495082123e-11
0.039999999999999994  0.2000000000021489   3.333333333333333e-07  0.19999999999999998  2.1489199308888374e-12
0.045                 0.2121320343564145   3.333333333333333e-07  0.21213203435596426  4.5025094763673223e-13
0.049999999999999996  0.22360701085328497  3.333333333333333e-07  0.22360679774997896  2.131033060015497e-07
0.05499999999999999   0.23452089492897005  3.333333333333333e-07  0.23452078799117146  1.0693779858850228e-07
0.06                  0.2449490292954153   3.333333333333333e-07  0.2449489742783178   5.501709748889638e-08
--------------------  -------------------  ---------------------  -------------------  ----------------------

In [ ]:
table4 = [['x', 'Our z', 'delta1', 'True z', 'delta2']]
for i in x:
  table4.append([i, sq(sh(2*i+0.45, eps1), eps3)/arctan(6*i+1, eps2), eps, (math.sqrt(math.sinh(2*i+0.45)))/math.atan(6*i+1), abs((math.sqrt(math.sinh(2*i+0.45)))/math.atan(6*i+1)-sq(sh(2*i+0.45, eps1), eps3)/arctan(6*i+1, eps2))])
print(tabulate(table4))

--------------------  ------------------  ------  ------------------  ----------------------
x                     Our z               delta1  True z              delta2
0.01                  0.857207325035493   1e-06   0.8572072084920246  1.1654346843137375e-07
0.015                 0.8523897396680837  1e-06   0.8523896288313564  1.1083672735168193e-07
0.019999999999999997  0.8480806201374808  1e-06   0.8480804982306291  1.2190685161339587e-07
0.024999999999999998  0.8442396320352188  1e-06   0.8442395211001067  1.1093511209647744e-07
0.03                  0.8408303828986687  1e-06   0.8408304787144124  9.581574367256707e-08
0.034999999999999996  0.8378208556970829  1e-06   0.8378207347844748  1.2091260803703818e-07
0.039999999999999994  0.8351810291188124  1e-06   0.8351808112647802  2.1785403225837996e-07
0.045                 0.8328841796160139  1e-06   0.8328840229652864  1.5665072750081777e-07
0.049999999999999996  0.8309062523877678  1e-06   0.8309061616280685  9.075969931160444e-08
0.05499999999999999   0.8292252387839807  1e-06   0.8292252217967978  1.6987182882566287e-08
0.06                  0.8278213510338318  1e-06   0.8278211621456613  1.8888817054918405e-07
--------------------  ------------------  ------  ------------------  ----------------------